services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./core_database/init-db:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - dokploy-network

  dashboard:
    image: python:3.11
    working_dir: /dashboard
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./dashboard:/dashboard
    command: ["sh", "-c", "pip install --no-cache-dir -r requirements.txt && streamlit run main.py --server.port=8501 --server.address=0.0.0.0 --server.enableCORS=false"]
    ports:
      - "8501:8501"
    networks:
      - dokploy-network
  

volumes:
  db_data:

networks:
  dokploy-network:
    external: false
